[virtualenvs]
path = ".venv"
in-project = true

[virtualenvs.options]
prefer-active-python = true

[settings]
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.path = ".venv"
python = "/opt/homebrew/bin/python3" 