global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@financehub.com'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 5m
    - match:
        service: external-api
      receiver: 'external-api-alerts'
    - match:
        service: redis
      receiver: 'infrastructure-alerts'
    - match:
        service: system
      receiver: 'infrastructure-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://host.docker.internal:5001/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://host.docker.internal:5001/webhook/critical'
        send_resolved: true

  - name: 'external-api-alerts'
    webhook_configs:
      - url: 'http://host.docker.internal:5001/webhook/external'
        send_resolved: true

  - name: 'infrastructure-alerts'
    webhook_configs:
      - url: 'http://host.docker.internal:5001/webhook/infra'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service'] 